blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/moatazeldebsy/test-automation-practices/discussions
    about: Please ask and answer questions here.